version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mygisdb
      POSTGRES_USER: mygisuser
      POSTGRES_PASSWORD: mygispassword
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db

  postgis:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: mygisdb
      POSTGRES_USER: mygisuser
      POSTGRES_PASSWORD: mygispassword
    depends_on:
      - db

  dozzle:
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_HOSTNAME: 'munywele.co.ke'
    ports:
      - 9999:8080
