version: '3.1'
name: "agwise-postgis"

services:

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "5050:80"
    depends_on:
      - postgis
    links:
      - "postgis"
    volumes:
      - pg-admin:/var/lib/pgadmin

  postgis:
    container_name: postgis
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: agwise_db
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
    - agwise-pg:/var/lib/postgresql/data

  dozzle:
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_HOSTNAME: 'munywele.co.ke'
    ports:
      - 9999:8080

volumes:
  agwise-pg:
  pg-admin: