version: '3.1'

services:

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@akilimo.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    links:
      - postgis""

  postgis:
    container_name: postgis
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: mygisdb
      POSTGRES_USER: mygisuser
      POSTGRES_PASSWORD: mygispassword
    volumes:
    - pgdata:/var/lib/postgresql/data

  dozzle:
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_HOSTNAME: 'munywele.co.ke'
    ports:
      - 9999:8080

volumes:
  pgdata: